### ISSUE TITLE
Fix issues with collations and encoding in mysql

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/revs#12]
It appears our MySQL character sets and collations are not set to UTF-8.  This can cause problems when users try to use UTF-8 character sets when querying against the database (such as when doing autocomplete).  The error received is 

> Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for
Request

For example, see this squash bug:

https://sul-squash-prod.stanford.edu/projects/revs-digital-library/environments/production/bugs/102

We may need to update our MySQL tables character sets and collations to UTF-8.   We should do this for both revs and editstore.

---
Examples of images with special characters...search for "Nurburgring" 

e.g. https://revslib.stanford.edu/catalog/rf182yv2435

---
1. backup/dump plain without any options (dump schema):

  ````
  mysqldump -urevs -pPASSWORDHERE --default-character-set=latin1 --skip-set-charset --no-data revs > revs_schema.sql
  ````

2. Edit schema dump file to
 
 1. use utf8_unicode_ci collation in table create 
 2. use charset utf8 

3. dump data as charset=utf8:

  ````
   mysqldump -urevs -pPASSWORDHERE --default-character-set=utf8 --skip-set-charset --no-create-info revs > revs.data.sql 
  ````

4. Drop the database:

  ````
  mysql -urevs -pPASSWORDHERE
  ````

  ````
  drop database revs; 
  ````

5. Create the database again with UTF-8 :

  ````
  mysql -urevs -pPASSWORDHERE
  ````

  ````
  create database revs character set utf8 collation utf8_unicode_ci; 
  ````

6. import schema:

  ````
   mysql -urevs -pPASSWORDHERE --default-character-set=utf8 revs < revs_schema.sql 
  ```

7. import data:

  ```
   mysql -urevs -pPASSWORDHERE --default-character-set=utf8 revs < revs.data.sql
  ```

---
Use second method on this page: 

http://ronaldbradford.com/blog/migrating-mysql-latin1-to-utf8-the-process-2010-03-06/ 

But watch out for double encoded (UTF-8 to latin1). Rails app specifies utf-8 in database.yml, which means the utf-8 chars coming from rails my be latin1 encoded at the database. Need to check for this and dump. See Willy's example.

**Comment by peetucket** [comment]
http://stackoverflow.com/questions/22464011/mysql2error-incorrect-string-value
