### ISSUE TITLE
Make 'Filter by archive' pulldown dynamic

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/revs#15]
The collection results page now has a pulldown menu for filtering by archive. The menu choices are now static, however, and don't create a new query.

Need to populate the pulldown menu with existing archives dynamically, and create a new collections query so that selecting an archive from the menu refreshes the page with only collections from archive selected.

**Comment by peetucket** [comment]
How do you indicate which item is selected in drop-down?  Is there a class to apply?  When the user has filtering applied, we should select that item in the drop-down.  

I also added an "All" option to remove filtering if it had been selected.
