### ISSUE TITLE
Exclude collection objects?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/revs#24]
Since we've introduced the notion of "archive" into the site, it looks like we're mixing collection objects in where they ideally should be excluded. For example, in the screenshot below the R&T archive only has two items, but the collection object itself is included in the facet count and a thumbnail for it is shown in the results, which looks less than ideal (alignment off, no item metadata).  

It's seems unlikely that  a user would want to click on a collection object (if they're interested in collections, there's the main menu and facet links). Can we exclude collection objects being counted in facets and not show in search results?

![revs_digital_library__search](https://cloud.githubusercontent.com/assets/101482/9533154/ec5442c0-4cc4-11e5-8b3b-1efa41e68b51.png)

**Comment by peetucket** [comment]
Yup.  I think it is because that query does a "is member of archive" and does not further restrict to items only.  We may be able to alter that facet query with some blacklight jujitsu.  Will investigate tomorrow.

**Comment by peetucket** [comment]
@ggeisler: pull and check out the develop branch - i think i was able to do a custom query to ignore collection objects when running the archive facet query

**Comment by ggeisler** [comment]
Yep, looks great. Thanks.
