### ISSUE TITLE
Add the ability to store a custom saved query and show on home page

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/revs#70]
It would be useful for curators to have a custom saved query appear on the home page or in the facet bar.  The custom query should be settable in the admin interface (and locked down to only admins to ensure it is valid).  The query will show for curators and will often be something like "lowest scores in a specific collection"

**Comment by ggeisler** [comment]
I think this would be best if we could keep in the facet sidebar. Presumably a curator could want to store several (even a large handful?) saved queries and I can't see a good way to display those directly on the homepage without it getting very ugly very quickly.

But as a curator-only facet, I think it would have no impact on the homepage, while being a convenient way to store multiple custom queries. It also makes sense there in that we already show curator-only things there (e.g., hidden items).

**Comment by peetucket** [comment]
Agreed.  This is also the easiest way to implement it.  I was thinking of something rather simple, like you enter a query (or queries) and label (or labels), and it uses that in the facet.  This makes it less user friendly than Spotlight, where you just execute a query and hit the save button, but more flexible, since I can enter queries that can otherwise not be run on the site, like metadata score > 5 and < 20).

**Comment by peetucket** [comment]
Do you have a suggestion for the label on the facet bar?  Jessica at Revs suggested "Crowdsourcing"..not sure what I think about that, but haven't come up anything better ("Curators List"?)

The label for the queries would be entered in the admin interface

**Comment by ggeisler** [comment]
Sure, sounds good. Since it's curator-only it seems safe to assume the limited number of people that would use the feature can be expected to understand how to enter a query.

So there needs to be a new page linked under the Actions section in the Curator section? Let me know if you want a design for it, but you could probably just follow the general layout of the Create New Gallery page.

**Comment by ggeisler** [comment]
I'm definitely not a fan of "Crowdsourcing." Doesn't really describe what it is at all.

Why not just "Saved Searches" or "Saved Queries"? Only curators will see it, and they are creating them by saving searches/queries, so that seems most direct.

**Comment by peetucket** [comment]
I can follow the template for the admin interface.  I was going to limit to admins only to avoid a curator doing inadvertent damage.

"Saved Searches" sounds good and generic enough.

**Comment by ggeisler** [comment]
Or "Custom Queries"?

Does a given curator see all the saved searches, or only the ones that curator saved?

**Comment by peetucket** [comment]
Curator would see all of them (curators can't create their own, they would be global for all curators).

**Comment by ggeisler** [comment]
Got it. Sounds good.

**Comment by peetucket** [comment]
Actually, Jessica thought it would be useful to have at least some queries showing for all users, to help draw in web users to help identify images that need help.  Technically this is straightforward, but she was hoping to have a label that would draw people in more (she suggested "Special Identification", which is not descriptive enough).

**Comment by ggeisler** [comment]
I see. That's probably why she initially suggested "Crowdsourcing." That label makes more sense if you're exposing it to end-users with the goal of getting them to improve the metadata. Though it still doesn't seem ideal, nor does "Special Identification."

Nothing is coming to me now, but if I think of something better than those, I'll let you know.
